apiVersion: apps/v1
kind: Deployment
metadata:
  name: linuxcoreapp2
  labels:
    app: linuxcoreapp2
spec:
  replicas: 1
  template:
    metadata:
      name: linuxcoreapp2
      labels:
        app: linuxcoreapp2
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: linuxcoreapp2
        image: hwacrpoc.azurecr.io/linuxcoreapp2
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret1

  selector:
    matchLabels:
      app: linuxcoreapp2
---
apiVersion: v1
kind: Service
metadata:
  name: linuxcoreapp2
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: linuxcoreapp2