apiVersion: apps/v1
kind: Deployment
metadata:
  name: windowscoreapp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windowscoreapp3
  template:
    metadata:
      labels:
        app: windowscoreapp3
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      tolerations:
      - key: key1
        operator: Equal
        value: value1
        effect: NoSchedule
      containers:
      - name: windowscoreapp3
        image: hwacrpoc.azurecr.io/windowscoreapp3
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret1
---
apiVersion: v1
kind: Service
metadata:
  name: windowscoreapp3
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: windowscoreapp3
