apiVersion: apps/v1
kind: Deployment
metadata:
  name: windowscoreapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windowscoreapp1
  template:
    metadata:
      labels:
        app: windowscoreapp1
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: windowscoreapp1
        image: hwacrpoc.azurecr.io/windowscoreapp1
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret1
---
apiVersion: v1
kind: Service
metadata:
  name: windowscoreapp1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: windowscoreapp1
