apiVersion: apps/v1
kind: Deployment
metadata:
  name: windowscoreapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windowscoreapp2
  template:
    metadata:
      labels:
        app: windowscoreapp2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: windowscoreapp2
        image: hwacrpoc.azurecr.io/windowscoreapp1:nano20h2
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret1
---
apiVersion: v1
kind: Service
metadata:
  name: windowscoreapp2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: windowscoreapp2
